[font]
size = 12.25

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
