#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

if [ -z "$@" ]
then
    echo -en "\x00prompt\x1fSnippets\n"
    echo -en "\0markup-rows\x1ftrue\n"
    ls $SCRIPTPATH/snippets
else
  cat $SCRIPTPATH/snippets/$1 | xsel -i
  cat $SCRIPTPATH/snippets/$1 | xsel -i -b
  # coproc (xdotool type --clearmodifiers --delay 20 --file $SCRIPTPATH/snippets/$1)
  coproc (xdotool key Shift+Insert)
fi
